_COUNTRY_CURRENCY = {
    "IN": "₹",
    "US": "$",
    "GB": "£",
    "EU": "€",
    "DE": "€",
    "FR": "€",
    "IT": "€",
    "ES": "€",
    "NL": "€",
    "BE": "€",
    "AT": "€",
    "IE": "€",
    "PT": "€",
    "GR": "€",
    "FI": "€",
    "LU": "€",
    "SK": "€",
    "SI": "€",
    "EE": "€",
    "LV": "€",
    "LT": "€",
    "MT": "€",
    "CY": "€",
    "HR": "€",
    "AU": "A$",
    "CA": "C$",
    "JP": "¥",
    "CN": "¥",
    "KR": "₩",
    "SG": "S$",
    "MY": "RM",
    "TH": "฿",
    "VN": "₫",
    "PH": "₱",
    "ID": "Rp",
    "PK": "₨",
    "BD": "৳",
    "NG": "₦",
    "ZA": "R",
    "KE": "KSh",
    "GH": "GH₵",
    "TZ": "TSh",
    "UG": "USh",
    "EG": "E£",
    "SA": "﷼",
    "AE": "د.إ",
    "QA": "﷼",
    "KW": "د.ك",
    "BH": "د.ب",
    "OM": "﷼",
    "CH": "CHF",
    "SE": "kr",
    "NO": "kr",
    "DK": "kr",
    "PL": "zł",
    "CZ": "Kč",
    "HU": "Ft",
    "RO": "lei",
    "BG": "лв",
    "TR": "₺",
    "IL": "₪",
    "MX": "$",
    "BR": "R$",
    "AR": "$",
    "CL": "$",
    "CO": "$",
    "PE": "S/",
}


def get_currency_symbol(country_code: str | None) -> str:
    if not country_code:
        return ""
    return _COUNTRY_CURRENCY.get(country_code.upper(), "")
