export const P = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_FINANCIAL: 'dashboard.financial',
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  SALES_DELETE: 'sales.delete',
  SALES_RETURNS_MANAGE: 'sales_returns.manage',
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_EDIT: 'purchases.edit',
  PURCHASES_DELETE: 'purchases.delete',
  PURCHASE_RETURNS_MANAGE: 'purchase_returns.manage',
  PAYMENTS_MANAGE: 'payments.manage',
  CUSTOMERS_MANAGE: 'customers.manage',
  SUPPLIERS_MANAGE: 'suppliers.manage',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_EDIT: 'products.edit',
  STOCK_VIEW: 'stock.view',
  STOCK_ADJUST: 'stock.adjust',
  VIEW_PRODUCT_PROFIT: 'view_product_profit',
  EXPENSES_MANAGE: 'expenses.manage',
  REPORTS_VIEW: 'reports.view',
  STAFF_MANAGE: 'staff.manage',
  SETTINGS_MANAGE: 'settings.manage',
}
