export const selectStyle = {
  width: '100%',
  padding: '9px 36px 9px 12px',
  background: 'var(--bg-card)',
  border: '1.5px solid var(--border)',
  borderRadius: 10,
  fontSize: 13,
  fontWeight: 500,
  color: 'var(--text-primary)',
  fontFamily: 'var(--font-sans, "Plus Jakarta Sans", sans-serif)',
  outline: 'none',
  cursor: 'pointer',
  appearance: 'none',
  WebkitAppearance: 'none',
  backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%236366F1' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C%2Fpolyline%3E%3C%2Fsvg%3E")`,
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'right 10px center',
  backgroundSize: '16px 16px',
  transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
}

export const textareaStyle = {
  width: '100%',
  padding: '9px 12px',
  background: 'var(--bg-card)',
  border: '1.5px solid var(--border)',
  borderRadius: 10,
  fontSize: 13,
  fontWeight: 400,
  color: 'var(--text-primary)',
  fontFamily: 'var(--font-sans, "Plus Jakarta Sans", sans-serif)',
  outline: 'none',
  resize: 'vertical',
  minHeight: 80,
  lineHeight: 1.5,
  boxSizing: 'border-box',
}
